spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cqrs
    username: cqrs
    password: cqrs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
  jwt:
    algorithm: HS256
    secret-key: cqrs
    expire-second: 604800
    refresh-expire-second: 129600
  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:postgresql://localhost:5432/cqrs
    user: cqrs
    password: cqrs
    locations: classpath:db/migration
logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error