spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cqrs
    username: cqrs
    password: cqrs
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
  jwt:
    algorithm: HS256
    secret-key: cqrs
    expire-second: 604800
    refresh-expire-second: 129600
  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:postgresql://localhost:5432/cqrs
    user: cqrs
    password: cqrs
    locations: classpath:db/migration
logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
cloud:
  aws:
    credentials:
      access-key: accesskey
      secret-key: secretkey
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sns:
      arns:
        create-user: arn:aws:sns:ap-northeast-2:000000000000:CreateUser
        update-user: arn:aws:sns:ap-northeast-2:000000000000:UpdateUser
        delete-user: arn:aws:sns:ap-northeast-2:000000000000:DeleteUser
        create-article: arn:aws:sns:ap-northeast-2:000000000000:CreateArticle
        update-article: arn:aws:sns:ap-northeast-2:000000000000:UpdateArticle
        delete-article: arn:aws:sns:ap-northeast-2:000000000000:DeleteArticle
        create-article-comment: arn:aws:sns:ap-northeast-2:000000000000:CreateArticleComment
        update-article-comment: arn:aws:sns:ap-northeast-2:000000000000:UpdateArticleComment
        delete-article-comment: arn:aws:sns:ap-northeast-2:000000000000:DeleteArticleComment
    sqs:
      url: http://localhost:4566
      queue:
        create-user: create-user
        update-user: update-user
        delete-user: delete-user
        create-article: create-article
        update-article: update-article
        delete-article: delete-article
        create-article-comment: create-article-comment
        update-article-comment: update-article-comment
        delete-article-comment: delete-article-comment