CREATE table users (
    id int8 generated by default as identity,
    create_time timestamp,
    update_time timestamp,
    email varchar(100) not null,
    nickname varchar(20) not null,
    password varchar(255) not null,
    primary key (id)
);