CREATE table article (
    id int8 generated by default as identity,
    user_id int8,
    create_time timestamp,
    update_time timestamp,
    title varchar(30) not null,
    description varchar(255) not null,
    primary key (id)
);

CREATE table article_comment (
    id int8 generated by default as identity,
    user_id int8,
    article_id int8,
    create_time timestamp,
    update_time timestamp,
    body varchar(255) not null,
    primary key (id)
);

alter table if exists article
add constraint FK5gj2wpe2fsrpm2jfnlbq88dlk
foreign key (user_id)
references users;

alter table if exists article_comment
add constraint FKf0dvop3xf5orf5j8icdwnq5ak
foreign key (article_id)
references article;

alter table if exists article_comment
add constraint FKf0ddop3xf5ora5j8icdwnq5ao
foreign key (user_id)
references users;